//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursePerson
    {
        public int personID { get; set; }
        public string PersonLogin { get; set; }
        public string personPassword { get; set; }
        public int personRole { get; set; }
        public string personLastName { get; set; }
        public string personFirstName { get; set; }
    
        public virtual CursePersonRole CursePersonRole { get; set; }
    }
}
